version: '3'

services:
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      environment:
        DB_VENDOR: H2
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        KEYCLOAK_IMPORT: /realm-export.json
      volumes:
      - ./realm-export.json:/realm-export.json
      ports:
      - 8080:8080

  oauth2:
      image: quay.io/oauth2-proxy/oauth2-proxy
      depends_on:
      - keycloak
      - webrtc      
      command: --config /etc/oauth2-proxy.cfg
      volumes:
      - ./oauth2-proxy.cfg:/etc/oauth2-proxy.cfg
      ports:
      - 80:4180
      
  nginx:
    image: nginx
    depends_on:
    - oauth2
    expose:
    - 8080
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf   

  webrtc:
    image: mpromonet/webrtc-streamer
    expose:
    - 8000
      

    
