version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: H2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /realm-export.json
    volumes:
    - ./realm-export.json:/realm-export.json
    expose:
    - 8080

  oauth2:
    image: quay.io/oauth2-proxy/oauth2-proxy
    depends_on:
    - keycloak
    entrypoint: /bin/sh
    command: 
      - -c 
      - |
        echo "waiting for keycloak"
        until wget -q --spider keycloak:8080 2>/dev/null
        do
          echo "."
          sleep 1
        done
        exec oauth2-proxy --config /etc/oauth2-proxy.cfg
    volumes:
    - ./oauth2-proxy.cfg:/etc/oauth2-proxy.cfg
    expose:
    - 4180
      
  nginx:
    image: nginx
    depends_on:
    - oauth2
    - webrtc      
    ports:
    - 80:80
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf   

  webrtc:
    image: mpromonet/webrtc-streamer
    expose:
    - 8000
      

    
