error_log /dev/stdout debug;

server {
    listen 80;
    proxy_buffers 4 256k;
    proxy_buffer_size 128k; 
    proxy_busy_buffers_size 256k;

    location = /oauth2/auth {
      internal;
      proxy_pass       http://oauth2:4180;
      proxy_set_header Host             $host;
      proxy_set_header X-Real-IP        $remote_addr;
      proxy_set_header X-Scheme         $scheme;
      proxy_set_header Content-Length    "";
      proxy_pass_request_body           off;
      proxy_connect_timeout             5s;
      proxy_read_timeout                10s;
    }

    location /oauth2/ {
      proxy_pass       http://oauth2:4180;
      proxy_set_header Host                    $host;
      proxy_set_header X-Real-IP               $remote_addr;
      proxy_set_header X-Scheme                $scheme;
      proxy_set_header X-Auth-Request-Redirect $request_uri;
    }

    location = /oauth2/sign_in {
      proxy_pass       http://oauth2:4180;
      proxy_set_header Host                    $host;
      proxy_set_header X-Real-IP               $remote_addr;
      proxy_set_header X-Scheme                $scheme;
      proxy_set_header X-Auth-Request-Redirect $scheme://$host;
    }

    location = /oauth2/sign_out {
      proxy_pass       http://oauth2:4180;
      proxy_set_header Host                    $host;
      proxy_set_header X-Real-IP               $remote_addr;
      proxy_set_header X-Scheme                $scheme;
      proxy_set_header X-Auth-Request-Redirect $scheme://$host/auth/realms/myrealm/protocol/openid-connect/logout?redirect_uri=$scheme://$host/oauth2/sign_in;
    }

    location / {
      auth_request /oauth2/auth;
      error_page 401 = /oauth2/sign_in; 

      auth_request_set $authorization $upstream_http_authorization;
      proxy_set_header Authorization $authorization;

      proxy_pass http://webrtc:8000/;
    }

    location /auth {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Port $server_port;
 
      proxy_pass http://keycloak:8080/auth;
    }       
}

